### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by gil00pita** [hooram/ownphotos-backend#105]
Hi guys, I am excited to try Ownphotos as docker container but when I try to login I am getting this error.
![TypeError: Cannot read property 'status' of undefined
    at http://10.20.30.23:8154/static/js/bundle.js:259704:22](https://i.imgur.com/99bzYJX.png?dl=0"Error")
```
TypeError: Cannot read property 'status' of undefined
    at http://10.20.30.23:8154/static/js/bundle.js:259704:22
```

Could anybody help me with this?

**Comment by malbert911** [comment]
Hey, I had the same error as you.
Presuming you are accessing the frontend at http://10.20.30.23:8154, it is trying to access your backend at localhost:3000

You might want to have a look at the BACKEND_HOST variable in the docker_compose.yml and change it to whatever you are externally accessing the frontend at. most likely 10.20.30.23:8154 in your case.

Cheers
