### ISSUE TITLE
Could not find a version that satisfies the requirement en-core-web-sm==2.0.0 mkl-random==1.0.1

### ISSUE THREAD

**Issue by guysoft** [hooram/ownphotos-backend#44]
Getting
```
Could not find a version that satisfies the requirement en-core-web-sm==2.0.0
```

And after removing that I get:

```
Could not find a version that satisfies the requirement mkl-random==1.0.1
```
When running ``pip install -r requirements.txt`` from this repo.

**Comment by guysoft** [comment]
It looks like the whole dockerfile container is broken, I am getting:

```
  Downloading https://files.pythonhosted.org/packages/28/39/439638bc21fc958859f98c432823bd6127eb1dfc93962fc7c67fa0f749cc/pyocclient-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ryy9hnwx/pyocclient/setup.py", line 18, in <module>
        + '\n')
      File "/venv/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 229: ordinal not in range(128)
```

It looks like the container is broke, I warmly suggest moving to an automated build. I will see if I can stabilize it and PR

**Comment by guysoft** [comment]
Fixed, there is a PR for this at: https://github.com/hooram/ownphotos/pull/45

**Comment by guysoft** [comment]
This is fixed and merged
