### ISSUE TITLE
Ownphotos fails to start, complains about COCO import 

### ISSUE THREAD

**Issue by guysoft** [hooram/ownphotos-backend#56]
Looks like something in the container breaks ``/code/api/im2txt/build_vocab.py``

There is an import there ``from pycocotools.coco import COCO``

Which now gives in the commandline:

```
>>> from pycocotools.coco import COCO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.5/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/venv/lib/python3.5/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "__init__.pxd", line 918, in init pycocotools._mask
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
>>> 
```

**Comment by guysoft** [comment]
Better commit message could be "switched from pip to conda". Because switching to Anaconda is also a distribution/support decision.
