### ISSUE TITLE
Errors during photo scan

### ISSUE THREAD

**Issue by danielsjf** [hooram/ownphotos-backend#60]
I used the trick mentioned in #51  to view the progress of the scan for new photos. Here I noticed lots of error messages concerning the date times. It also seems that this affects the results as many photos have missing timestamps.

It must be said that long after the counter reached 100%, the "Scan Photos" is still active.

```
12it [00:04,  2.65it/s]1
1
4832548215a188a3bfd991c2071300501
64ee96024ed9f9e43bee7615212a9f4b1
/venv/lib/python3.5/site-packages/django/db/models/fields/__init__.py:1421: RuntimeWarning: DateTimeField Photo.exif_tim
estamp received a naive datetime (2017-10-28 12:55:41) while time zone support is active.
  RuntimeWarning)
photo not added to album place
Error in directory scan, got exception:
duplicate key value violates unique constraint "api_photo_pkey"
DETAIL:  Key (image_hash)=(64ee96024ed9f9e43bee7615212a9f4b1) already exists.

Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "api_photo_pkey"
DETAIL:  Key (image_hash)=(64ee96024ed9f9e43bee7615212a9f4b1) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/api/directory_watcher.py", line 117, in handle_new_image
    photo._add_to_album_thing()
  File "/code/api/models.py", line 511, in _add_to_album_thing
    album_thing.cover_photos.add(self)
  File "/venv/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 926, in add
    self._add_items(self.source_field_name, self.target_field_name, *objs)
  File "/venv/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 1075, in _add_items
    new_ids.difference_update(vals)
  File "/venv/lib/python3.5/site-packages/django/db/models/query.py", line 268, in __iter__
    self._fetch_all()
  File "/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/venv/lib/python3.5/site-packages/django/db/models/query.py", line 176, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1017, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/venv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "api_photo_pkey"
DETAIL:  Key (image_hash)=(64ee96024ed9f9e43bee7615212a9f4b1) already exists.
```

The error also mentions duplicate key, while the scan details seem to indicate that an md5 check should avoid this.

**Comment by hooram** [comment]
Can you try pulling the newest backend docker image and try again?

**Comment by danielsjf** [comment]
Sure thing!

**Comment by danielsjf** [comment]
After the upgrade, I have the same error as #52. I'll try to debug that first in the weekend. I'll get back to you when I have this fixed.

(by the way, my latest pull before was only from a couple of days ago)

**Comment by hooram** [comment]
The latest commit 4a643a0c3c0dffc9821e699b1f2b9cdb8e8f24c2 should fix a number of bugs, including this issue you posted. There are two things I changed in the last commit:

- switch to miniconda for installing some python packages, namely pytorch - related to #56 
- disable parallel importing of photos, which can attempt to import the same photo in multiple processes, which would cause the DB to poop out saying `DETAIL:  Key (image_hash)=(64ee96024ed9f9e43bee7615212a9f4b1) already exists.` like in the log above. 

In the log you posted above, I can tell that the docker image isn't the latest one, because python site-packages should be in `/miniconda/lib/python3.7/.....`, not `/venv/lib/python3.5/.....`, as it shows in your log. Could you try and `docker exec -it ownphotos-backend /bin/bash` or so and see if the path `/miniconda` exists in the container?

It will probably help to start everything fresh, by `docker-compose down -v --rmi all` or so.

**Comment by danielsjf** [comment]
Alright so I updated to the newest version but I still get these timezone warnings.

For your reference, I'm working on Windows which might be relevant for this issue.

```
0a75651f43ebd6038d2835fd758fc0561
/miniconda/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1421: RuntimeWarning: DateTimeField Photo.exi
f_timestamp received a naive datetime (2017-10-29 15:09:43) while time zone support is active.
  RuntimeWarning)
photo not added to album place
  1%|          | 61/6315 [03:36<5:49:32,  3.35s/it]1
4b6a8381a6fd0283f4b1a98108962fe01
```
However, it seems that my photos do get timezone tagged. I guess this can be closed.

**Comment by hooram** [comment]
Thanks for reporting back. Theres another issue for the timezone problem, so I'll close this.

**Comment by danielsjf** [comment]
For future reference, that other issue is #35
