### ISSUE TITLE
ValueError: No group keys passed!

### ISSUE THREAD

**Issue by danielsjf** [hooram/ownphotos-backend#62]
Many faces process well, but I do get quite a lot of these errors (all of the same type). I don't know if this is the reason why quite a few faces remain untagged. In any case, I'll further explore your brilliant work 👍 

```
serializing photos of faces took 0.01 seconds
Unauthorized: /api/rqavailable/
Internal Server Error: /api/locationsunburst/
Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/venv/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/venv/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/venv/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/api/views.py", line 1727, in get
    res = get_location_sunburst()
  File "/code/api/api_util.py", line 330, in get_location_sunburst
    df.columns.tolist()).size().reset_index().rename(columns={4: 'count'})
  File "/venv/lib/python3.5/site-packages/pandas/core/generic.py", line 6665, in groupby
    observed=observed, **kwargs)
  File "/venv/lib/python3.5/site-packages/pandas/core/groupby/groupby.py", line 2152, in groupby
    return klass(obj, by, **kwds)
  File "/venv/lib/python3.5/site-packages/pandas/core/groupby/groupby.py", line 599, in __init__
    mutated=self.mutated)
  File "/venv/lib/python3.5/site-packages/pandas/core/groupby/groupby.py", line 3320, in _get_grouper
    raise ValueError('No group keys passed!')
ValueError: No group keys passed!
serializing photos of faces took 0.01 seconds
/venv/lib/python3.5/site-packages/rest_framework/pagination.py:198: UnorderedObjectListWarning: Pagination may yield inc
onsistent results with an unordered object_list: <class 'api.models.Person'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
```

**Comment by hooram** [comment]
Are your photos geotagged, and did you specify your mapbox api key in your docker-compose file? The error in your log doesn't seem to be about face recognition, but about `/api/locationsunburst/`, which is called when you go to Data Vis - Place Tree in the front end.

**Comment by danielsjf** [comment]
Indeed, I didn't have this key defined. However, I've added the key, but I still have these errors. Also my locations don't seem to work. I've restarted the containers and even Docker, but no difference.

Is there a special way in which I should use the key?

**Comment by guysoft** [comment]
If you change an environment variable in the container, such as the Mapbox
key, you need recreate the container, not just restart it.
Use
```
docker-compose up -d
```

**Comment by danielsjf** [comment]
I finally used the following commands to make it work.

``` 
docker-compose stop
docker-compose rm
docker-compose up -d --force-recreate
```
