### ISSUE TITLE
Getting 500 error after upgraded to latest

### ISSUE THREAD

**Issue by vkadam** [hooram/ownphotos-backend#82]
Hi,

Getting 500 errors on request of thumbnail after upgraded to latest docker/commit e40bc6ccd1f53d1cd3a84777d2ddd452a87da195. Error was like following
```
Internal Server Error: /api/searchtermexamples/
Traceback (most recent call last):
  File "/miniconda/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column api_photo.encoding does not exist
LINE 1: ...n", "api_photo"."owner_id", "api_photo"."public", "api_photo...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/miniconda/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/miniconda/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/miniconda/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/miniconda/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/miniconda/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/miniconda/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/miniconda/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/miniconda/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/api/views.py", line 1605, in get
    search_term_examples = get_search_term_examples(request.user)
  File "/code/api/api_util.py", line 130, in get_search_term_examples
    samples = random.sample(list(pp.all()), 100)
  File "/miniconda/lib/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__
    self._fetch_all()
  File "/miniconda/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/miniconda/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/miniconda/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/miniconda/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/miniconda/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/miniconda/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/miniconda/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/miniconda/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/miniconda/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column api_photo.encoding does not exist
LINE 1: ...n", "api_photo"."owner_id", "api_photo"."public", "api_photo...
                                                             ^
```

So alerted the table as per follow which solved the issue and thumbnails loaded 
```
ALTER TABLE "api_photo"
ADD "encoding" character varying(100) NULL;
COMMENT ON TABLE "api_photo" IS '';
```
Not sure this is correct type and/or size so haven't made the PR for change and reporting as bug.

**Comment by hooram** [comment]
Looks like migrations don't work properly with the current setup. Will have to look into this if we want people to not have to nuke their DBs and start everything over

**Comment by partyant** [comment]
@hooram the migrations in the project were not set up to work with existing databases, please see my fix in PR #80 for the auto_scan option

**Comment by hooram** [comment]
@partyant okay great! I will do a migration based off of yours and commit that too.
