### ISSUE TITLE
Getting Error 500 For Multiple Requests

### ISSUE THREAD

**Issue by coxtor** [hooram/ownphotos-backend#94]
Hello, I have setup everything with traefik using this docker-compose file. All appears to work fine.

```
version: '3'

services:
        
  frontend:
    image: hooram/ownphotos-frontend:dev
    container_name: ownphotos-frontend
    #build: ../ownphotos-frontend
    tty: true
    #volumes:
    #   - ../ownphotos-frontend/src:/usr/src/app/src
    environment:
      - BACKEND_HOST=ownphotos.${DOMAINNAME}

    depends_on:
      - backend   

    networks:
      - internal
      - proxy

    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:ownphotos.${DOMAINNAME}
      - traefik.backend=backend
      - traefik.port=3000   
      - traefik.docker.network=proxy         

  backend:
    image: hooram/ownphotos:dev
    # For development uncomment this and comment the image name above
    #build: .
    container_name: ownphotos-backend
    volumes:
      - /media/data/ownphotos/data/:/data # CHANGE ME
      - /media/data/ownphotos/thumbnails:/code/protected_media # CHANGE ME
      - /media/data/ownphotos/logs:/code/logs # CHANGE ME
    environment:
      - SECRET_KEY=${PW}
      - BACKEND_HOST=backend # DON'T CHANGE ME
      - ADMIN_EMAIL=${contactemail}
      - ADMIN_USERNAME=${adminuser}
      - ADMIN_PASSWORD=${adminpw}
      - DEBUG=false #true #false
      - DB_BACKEND=postgresql
      - DB_NAME=ownphotos
      - DB_USER=postgres
      # This db password is internal, you can change it if you want, but also change it in ownphotos-db container
      - DB_PASS=AaAa1234
      - DB_HOST=ownphotos-db
      - DB_PORT=5432
      - REDIS_HOST=ownphotos-redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=apikey # CHANGE ME - sign up at mapbox.com for an api key. You need this for reverse geocoding. 
    networks:
      - internal
      - proxy 

    depends_on:
      - ownphotos-redis      
      - ownphotos-db
    labels:
       - traefik.enable=true
       - traefik.frontend.rule=Host:ownphotos.${DOMAINNAME};Path:/api/ 
       - traefik.docker.network=proxy  

  ownphotos-redis:
    image: redis
    container_name: ownphotos-redis
    networks:
      - internal
    labels:
      - traefik.enable=false    

  ownphotos-db:
    image: postgres
    container_name: ownphotos-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=AaAa1234
      - POSTGRES_DB=ownphotos
    volumes:
      - ownphotos-data:/var/lib/postgresql/data
    networks:
      - internal
    labels:
      - traefik.enable=false   

volumes:
  ownphotos-data:
  media:

networks:
  proxy:
    external: true
  internal:
    external: false
```
Workers, jobs, thumbnails, logins, sharing all work fine. However, I get 500 Internal Server Error, when trying to favorite an image. 

Here some of the backends output when selecting as a favorite:
```

[2019-04-19 18:49:53,237] ERROR in app: Exception on /search/ [POST]
Traceback (most recent call last):
  File "image_similarity/main.py", line 39, in post
    res = index.search_similar(user_id,image_embedding,n)
  File "/code/image_similarity/retrieval_index.py", line 33, in search_similar
    res.append(self.image_hashes[user_id][idx])
IndexError: list index out of range

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/miniconda/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/miniconda/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/miniconda/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/miniconda/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/miniconda/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "image_similarity/main.py", line 44, in post
    return jsonify({'status':False,'result':[]},status=500)
  File "/miniconda/lib/python3.6/site-packages/flask/json.py", line 256, in jsonify
    raise TypeError('jsonify() behavior undefined when passed both args and kwargs')
TypeError: jsonify() behavior undefined when passed both args and kwargs
127.0.0.1 - - [2019-04-19 18:49:53] "POST /search/ HTTP/1.1" 500 164 0.038171

```

When attempting to open an image in full size:

```

[2019-04-19 18:51:59,967] ERROR in app: Exception on /search/ [POST]
Traceback (most recent call last):
  File "image_similarity/main.py", line 39, in post
    res = index.search_similar(user_id,image_embedding,n)
  File "/code/image_similarity/retrieval_index.py", line 33, in search_similar
    res.append(self.image_hashes[user_id][idx])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/miniconda/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/miniconda/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/miniconda/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/miniconda/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "image_similarity/main.py", line 44, in post
    return jsonify({'status':False,'result':[]},status=500)
  File "/miniconda/lib/python3.6/site-packages/flask/json.py", line 256, in jsonify
    raise TypeError('jsonify() behavior undefined when passed both args and kwargs')
TypeError: jsonify() behavior undefined when passed both args and kwargs
127.0.0.1 - - [2019-04-19 18:51:59] "POST /search/ HTTP/1.1" 500 164 0.011014
```

This is happening while workers are active.

Is any body else facing this issue?

**Comment by coxtor** [comment]
Update:
Apparently this issue resolves itself once the workers are finished.

**Comment by guysoft** [comment]
Should I close this or is there anything else to be done?

**Comment by coxtor** [comment]
I did not close it, as the issue of indexes being out of bounds under certain circumstances still persists. If you can confirm that this is a rare abnormality feel free to close it.
